# Generated by Django 5.0.1 on 2024-01-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0002_address_city_dayweek_speciality_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayweek',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
