# Generated by Django 5.0.1 on 2024-01-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0004_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='birth',
        ),
    ]
