# Generated by Django 5.0.1 on 2024-01-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0005_rename_birthday_profile_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth',
            new_name='birthday',
        ),
    ]
